site_name: Parallel process
site_url: https://parallel.readthedocs.io/
site_description: Introduce parallel computing
repo_url: https://github.com/WonyoungCho/parallel/
site_author: Wonyoung Cho

extra_javascript: [docs.js]

pages:
    - Home: 'index.md'
    - Linux shell:
        - 'Parallel' : 'parallel.md'

theme: readthedocs
